name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt-get update
          sudo apt-get install golang-go

      - name: Build project
        run: go build ./...

      - name: Create release
        id: create_release
        uses: actions/github-release@v1
        with:
          owner: ${{ github.actor }}
          repo: ${{ github.repository }}
          tag_name: ${{ github.ref }}
          body: |
            Build of ${{ github.commit }}.
          files: ./sactions
